stages:
  - build
  - create_image

build:
  image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/normal-tests:1.1.0
  stage: build
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME

    - mkdir -p ~/.ssh
    - touch ~/.ssh/known_hosts
    - ssh-keyscan -H 10.0.3.120 >> ~/.ssh/known_hosts

    - apt-get update
    - apt-get install -y libssl-dev libcrypto++-dev   libboost1.71-dev uuid-dev

    - cd /builds/kitsudaiki/ToriiGateway
    - ./build.sh

    - mkdir -p upload
    - cp ../result/ToriiGateway upload/

  artifacts:
    paths:
      - upload
    expire_in: 1 week
  tags:
    - docker

create_image:
  image: docker:20.10.11
  stage: create_image
  script:
    - mkdir -p /etc/docker
    - echo '{"insecure-registries":["10.0.2.10:5000"]}' > /etc/docker/daemon.json
    - docker build -t 10.0.2.10:5000/torii_gateway:$CI_COMMIT_BRANCH .
  dependencies:
    - build
  tags:
    - docker
